module.exports = {
  TOKEN_ERROR: 'Token not correct.',
  NO_TOKEN: 'Token required to access API.',
  INVALID_BODY: 'Request body is invalid.',
  DATA_SAVED: 'Request completed and data saved.',
  DATA_RETRIEVED: 'Request completed and data retrieved.',
  DATA_DELETED: 'Request completed and data deleted.',
  DATA_UPDATED: 'Request completed and data updated.',
  DATA_NOT_FOUND: 'Data not found against this query',
  FILE_NOT_FOUND: 'No file attached',
  PASSOWRD_MISMATCH: 'Old password did not match',
  PASSOWRD_ERROR: 'Password did not match',
  PASSWORD_UPDATED: 'Password has been updated',
  USER_NOTFOUND: 'User does not exist',
  USER_SIGNEDIN: 'User is signed-in',
  USER_LOGGEDIN: 'User is logged-in',
  USER_LOGGEDOUT: 'User is logged-out',
  UNABLE_DELETE: 'This cannot be deleted',
  EMAIL_EXIST: 'Email already exists',
};
