module.exports = {
  TOKEN_ERROR: new Error('Token not correct.'),
  NO_TOKEN: new Error('Token required to access API..'),
  INVALID_BODY: new Error('Request body is invalid.'),
  DATA_NOT_FOUND: new Error('Data not found against this query'),
  FILE_NOT_FOUND: new Error('No file attached'),
  PASSOWRD_MISMATCH: new Error('Old password did not match'),
  PASSOWRD_ERROR: new Error('Password did not match'),
  PASSWORD_UPDATED: 'Password has been updated',
  USER_NOTFOUND: new Error('User does not exist'),
  USER_SIGNEDIN: 'User is signed-in',
  USER_LOGGEDIN: 'User is logged-in',
  USER_LOGGEDOUT: 'User is logged-out',
  UNABLE_DELETE: new Error('This cannot be deleted'),
  EMAIL_EXIST: new Error('Email already exists'),
  DATA_SAVED: 'Request completed and data saved.',
  DATA_RETRIEVED: 'Request completed and data retrieved.',
  DATA_DELETED: 'Request completed and data deleted.',
  DATA_UPDATED: 'Request completed and data updated.',
};
